/*
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.68.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AccountsApi,
  BudgetsApi,
  CategoriesApi,
  MonthsApi,
  PayeeLocationsApi,
  PayeesApi,
  ScheduledTransactionsApi,
  TransactionsApi,
  UserApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { YnabCustom } from "./client-custom";

export class Ynab extends YnabCustom {
  readonly accounts: AccountsApi;
  readonly budgets: BudgetsApi;
  readonly categories: CategoriesApi;
  readonly months: MonthsApi;
  readonly payeeLocations: PayeeLocationsApi;
  readonly payees: PayeesApi;
  readonly scheduledTransactions: ScheduledTransactionsApi;
  readonly transactions: TransactionsApi;
  readonly user: UserApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.accounts = new AccountsApi(configuration);
    this.budgets = new BudgetsApi(configuration);
    this.categories = new CategoriesApi(configuration);
    this.months = new MonthsApi(configuration);
    this.payeeLocations = new PayeeLocationsApi(configuration);
    this.payees = new PayeesApi(configuration);
    this.scheduledTransactions = new ScheduledTransactionsApi(configuration);
    this.transactions = new TransactionsApi(configuration);
    this.user = new UserApi(configuration);
  }

}
