/*
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.68.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The currency format setting for the budget.  In some cases the format will not be available and will be specified as null.
 * @export
 * @interface CurrencyFormat
 */
export interface CurrencyFormat {
    /**
     * 
     * @type {string}
     * @memberof CurrencyFormat
     */
    'iso_code': string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFormat
     */
    'example_format': string;
    /**
     * 
     * @type {number}
     * @memberof CurrencyFormat
     */
    'decimal_digits': number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFormat
     */
    'decimal_separator': string;
    /**
     * 
     * @type {boolean}
     * @memberof CurrencyFormat
     */
    'symbol_first': boolean;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFormat
     */
    'group_separator': string;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFormat
     */
    'currency_symbol': string;
    /**
     * 
     * @type {boolean}
     * @memberof CurrencyFormat
     */
    'display_symbol': boolean;
}

