/*
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.68.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface HybridTransactionAllOf
 */
export interface HybridTransactionAllOf {
    /**
     * Whether the hybrid transaction represents a regular transaction or a subtransaction
     * @type {string}
     * @memberof HybridTransactionAllOf
     */
    'type': HybridTransactionAllOfTypeEnum;
    /**
     * For subtransaction types, this is the id of the parent transaction.  For transaction types, this id will be always be null.
     * @type {string}
     * @memberof HybridTransactionAllOf
     */
    'parent_transaction_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof HybridTransactionAllOf
     */
    'account_name': string;
    /**
     * 
     * @type {string}
     * @memberof HybridTransactionAllOf
     */
    'payee_name'?: string | null;
    /**
     * The name of the category.  If a split transaction, this will be \'Split\'.
     * @type {string}
     * @memberof HybridTransactionAllOf
     */
    'category_name'?: string;
}

type HybridTransactionAllOfTypeEnum = 'transaction' | 'subtransaction'


