/*
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.68.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SaveTransactionWithIdOrImportIdAllOf
 */
export interface SaveTransactionWithIdOrImportIdAllOf {
    /**
     * If specified, this id will be used to lookup a transaction by its `id` for the purpose of updating the transaction itself. If not specified, an `import_id` should be supplied.
     * @type {string}
     * @memberof SaveTransactionWithIdOrImportIdAllOf
     */
    'id'?: string | null;
    /**
     * If specified, this id will be used to lookup a transaction by its `import_id` for the purpose of updating the transaction itself. If not specified, an `id` should be supplied.  You may not provide both an `id` and an `import_id` and updating an `import_id` on an existing transaction is not allowed.
     * @type {string}
     * @memberof SaveTransactionWithIdOrImportIdAllOf
     */
    'import_id'?: string | null;
}

