/*
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.68.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SaveCategory
 */
export interface SaveCategory {
    /**
     * 
     * @type {string}
     * @memberof SaveCategory
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaveCategory
     */
    'note'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SaveCategory
     */
    'category_group_id'?: string;
}

