/*
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.68.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountType } from './account-type';

/**
 * 
 * @export
 * @interface SaveAccount
 */
export interface SaveAccount {
    /**
     * The name of the account
     * @type {string}
     * @memberof SaveAccount
     */
    'name': string;
    /**
     * The type of account
     * @type {AccountType}
     * @memberof SaveAccount
     */
    'type': AccountType;
    /**
     * The current balance of the account in milliunits format
     * @type {number}
     * @memberof SaveAccount
     */
    'balance': number;
}

