/*
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.68.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ScheduledSubTransaction } from './scheduled-sub-transaction';

/**
 * 
 * @export
 * @interface ScheduledTransactionDetailAllOf
 */
export interface ScheduledTransactionDetailAllOf {
    /**
     * 
     * @type {string}
     * @memberof ScheduledTransactionDetailAllOf
     */
    'account_name': string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledTransactionDetailAllOf
     */
    'payee_name'?: string | null;
    /**
     * The name of the category.  If a split scheduled transaction, this will be \'Split\'.
     * @type {string}
     * @memberof ScheduledTransactionDetailAllOf
     */
    'category_name'?: string | null;
    /**
     * If a split scheduled transaction, the subtransactions.
     * @type {Array<ScheduledSubTransaction>}
     * @memberof ScheduledTransactionDetailAllOf
     */
    'subtransactions': Array<ScheduledSubTransaction>;
}

